# Kokkuvõte {.unnumbered}

Elu, mida uuritakse bioloogia teaduses, mõistes ei ole teadlased üksmeelel. Organismid ja nende keskkonnad on looduslikud süsteemid, millele rakendatakse füüsika ja keemia kontseptsioone.

Organismid koosnevad ainest, aine elementidest. Keemiline ühend koosneb eri elementidest kindlas suhtes. Inimesed vajavad 25 elementi, taimed 17. Elusaine koosneb \qty{96}{\percent} hapnikust, süsinikust, vesinikust ja lämmastikust. Elus kõige suuremat rolli mängiva elemendi tunnused on rohkus, võimekus osaleda paljudes keemilistes reaktsioonides olles ühtlasi mitte liiga reaktiivne, moodustada ahelaid, ringe, harusid, lõkse, eri suurusega molekule, tegeleda üheaegselt mitme ülesandega, säilitada, paljundada ja tõlgendada teavet, moodustada vastupidavaid ja püsivaid membraane ja fiibreid, hankida, säilitada ja vabastada energiat. Kõikidele nendele tingimustele vastab ainult süsinik.

Süsinikul on neli valentselektroni, mis võimaldab süsinikul moodustada kuni neli sidet korraga. Ligi kümme miljonit süsinikuühendit on teada ja nendest mitmed tuhanded on olulised elulisteks ja orgaanilisteks protsessideks. Süsiniku ühendite uurimise teadus on orgaaniline keemia.

Süsinik avastati eelajalooliselt, kui seda kasutati söe ja kivisöena, millest tuleneb ka elemendi nimetus - süsi on ladina keeles *carbo*. Teemandid avastati Hiinas umbes 4500 a tagasi. 1786. a kinnitati, et grafiidi ja teemandi koostis on sama. Esimest korda loodi orgaaniline aine ilma elusaine osaluseta 1828. a.

Süsinik on universumis levikult neljandal kohal moodustudes peamiselt punastes hiiglastes. Looduses on süsinik amorfsena, grafiidina ja teemandina. Süsihappegaasi leidub ohtralt atmosfääris ja looduslikes veekogudes. Lubjakivina, magneesiumi ja raua ühenditena leidub süsinikku kivimassiivides. Süsi, petrooleum ja looduslik gaas on peamiselt süsivesinikud. inimese kehas on süsinik nelja levinuima elemendi seas. Kuna süsinikku leidub ümberringi niivõrd palju, arvestatakse kõikide keemiliste elementide suhtelist aatommassi süsiniku suhtelise aatommassi järgi, mille kohaselt on ühes moolis süsinikus täpselt \qty{12}{\g} süsinikku.

Süsinik suudab moodustada hiiglasliku arvu variatsioone eri pikkusega ahelaid. elusolendid osalevad nii süsiniku tootmises kui tarbimises süsinikuringe kaudu, mille üheks osaks on fotosüntees, milles taimed sünteesivad süsihappegaasist ja veest glükoosi ja hapniku ning hingavad olendid põletavad glükoosi energiaks ning eritavad süsihappegaasi ja vee. elusolendid, kes ei fotosünteesi, saavad süsinikuühendeid, tarbides muid elusolendeid. Süsinikuühendite talitluslikud rühmad, millest eluks vajalikud on hüdroksüül-, karboksüül-, amino-, sulfhüdrüül-, fosfaat- ja metüülgrupp, muudavad molekulide omadusi. Östradiool ja testosteroon erinevad üksteisest vaid kahes osas, kuid nende kaudu saab eristada sugusid. Adenosiintrifosfaat on rakkudes energiasalvesti. inimese toidus on süsinikuühendid rasvade, süsivesikute ja valkudenga ning lisaks mõjutavad inimese tervist ja olemust nukleiinhapped. Erinevate keemiliste omaduste tõttu mõjuvad need toitumises ja tervisele erinevalt.

Süsinik on element, mis tagab siinsetes tingimustes elu ja seda nii elusolendite siseselt kui ka väliselt vahendite koostises, mida elusolendid kasutavad.
